[project]
name = telegram_cjmp
description = A new keels project.
type = app
organization = com.example

# You can add other keels package or module project as dependencies.
# [dependencies]
# packageName = /path/to/package
# moduleName = /path/to/module
